# k8s/service.yaml
# Headless Service para que os Pods possam ser endereçados individualmente
apiVersion: v1
kind: Service
metadata:
  name: algoritmos-coord-service
spec:
  # Adicionar esta linha torna o serviço "headless"
  # Isso é crucial para que o StatefulSet crie os registros DNS corretos para cada pod.
  clusterIP: None
  selector:
    app: algoritmos-coord
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
